### ISSUE TITLE
About the project

### ISSUE THREAD

**Issue by dorrod-blip** [hiroppy/web-app-template#216]
Hello @hiroppy,

Nice to meet you.
Can I join your project as a web developer. I'm familiar web app development based on React, NextJS, Express and NestJS.

**Comment by hiroppy** [comment]
Yep, This is an OSS project

**Comment by dorrod-blip** [comment]
Thanks for your kindness.
I'm so pleasure to be with you. :)
Please send me an invitation in this repo.
And I have a question.
Is this project is your main job? I'd like to discuss more in your convenient chating platform.
